import { AppShell } from "@/components/app-shell";
import { TaskForm } from "@/components/forms";
import { updateTaskStatus } from "@/lib/actions";
import { Card, PageHeader, StatusBadge } from "@/components/ui";
import { genericList, listClients, listTasks, listUsers } from "@/lib/data";
import { dateShort } from "@/lib/format";
import type { Project } from "@/lib/types";
export const dynamic = "force-dynamic";
export default async function TasksPage() { const [tasks, users, projects, clients] = await Promise.all([listTasks(), listUsers(), genericList<Project>("projects"), listClients()]); return <AppShell><PageHeader eyebrow="Workload" title="Tasks" description="Cross-business task system linked to leads, clients, projects, tickets and internal admin." /><Card><TaskForm users={users.map((user) => ({ id: user.id, name: user.name }))} clients={clients} projects={projects.map((project) => ({ id: project.id, name: project.name, client_id: project.client_id }))} /></Card><div className="mt-6 grid gap-4 md:grid-cols-4">{[["Open", tasks.filter((task) => task.status !== "DONE").length], ["Overdue", tasks.filter((task) => task.due_date && new Date(task.due_date) < new Date() && task.status !== "DONE").length], ["Blocked", tasks.filter((task) => task.status === "BLOCKED").length], ["Done", tasks.filter((task) => task.status === "DONE").length]].map(([label, value]) => <Card key={label}><p className="text-sm text-slate-400">{label}</p><p className="mt-3 text-2xl font-bold text-white">{value}</p></Card>)}</div><div className="mt-6 overflow-hidden rounded-2xl border border-white/10"><table className="w-full bg-white/[0.035] text-sm"><thead className="bg-white/[0.06] text-left text-xs uppercase tracking-wider text-slate-400"><tr><th className="p-4">Task</th><th>Status</th><th>Priority</th><th>Assignee</th><th>Due</th></tr></thead><tbody>{tasks.map((task) => <tr key={task.id} className="border-t border-white/10"><td className="p-4 font-semibold text-white">{task.title}</td><td><form action={updateTaskStatus} className="flex items-center gap-2"><input type="hidden" name="id" value={task.id} /><input type="hidden" name="redirectTo" value="/tasks" /><select className="rounded-lg border border-white/10 bg-slate-950/70 px-2 py-1 text-xs" name="status" defaultValue={task.status}><option value="TO_DO">To Do</option><option value="IN_PROGRESS">In Progress</option><option value="WAITING_FOR_CLIENT">Waiting Client</option><option value="BLOCKED">Blocked</option><option value="DONE">Done</option></select><button className="rounded-lg border border-white/10 px-2 py-1 text-xs text-rapid-cyan">Save</button></form></td><td><StatusBadge value={task.priority} /></td><td><form action={updateTaskStatus} className="flex items-center gap-2"><input type="hidden" name="id" value={task.id} /><input type="hidden" name="status" value={task.status} /><input type="hidden" name="redirectTo" value="/tasks" /><select className="rounded-lg border border-white/10 bg-slate-950/70 px-2 py-1 text-xs" name="assignedToId" defaultValue={task.assigned_to ?? ""}><option value="">Unassigned</option>{users.map((user) => <option key={user.id} value={user.id}>{user.name}</option>)}</select><button className="rounded-lg border border-white/10 px-2 py-1 text-xs text-rapid-cyan">Assign</button></form></td><td>{dateShort(task.due_date)}</td></tr>)}</tbody></table></div></AppShell>; }
