import { AppShell } from "@/components/app-shell";
import { AcceptQuoteButton, QuoteForm } from "@/components/forms";
import { Card, EmptyState, PageHeader, StatusBadge } from "@/components/ui";
import { genericList, listClients, listLeads, listServices } from "@/lib/data";
import { money } from "@/lib/format";
import type { Quote } from "@/lib/types";
export const dynamic = "force-dynamic";
export default async function Quotes() {
  const [quotes, clients, leads, services] = await Promise.all([genericList<Quote>("quotes"), listClients(), listLeads(), listServices()]);
  return <AppShell><PageHeader eyebrow="Sales" title="Quotes" description="Create proposals, price once-off and monthly line items, send follow-ups and accept quotes into delivery." /><div className="grid gap-6"><Card><h2 className="mb-4 text-lg font-semibold">Create quote</h2><QuoteForm clients={clients} leads={leads} services={services} /></Card><div className="grid gap-4 md:grid-cols-5">{[["Total quotes", quotes.length], ["Quoted once-off", money(quotes.reduce((sum, quote) => sum + quote.once_off_total_cents, 0))], ["Quoted monthly", money(quotes.reduce((sum, quote) => sum + quote.monthly_total_cents, 0))], ["Accepted", quotes.filter((quote) => quote.status === "ACCEPTED").length], ["Follow-up due", quotes.filter((quote) => quote.status === "FOLLOW_UP_DUE").length]].map(([label, value]) => <Card key={label}><p className="text-sm text-slate-400">{label}</p><p className="mt-3 text-2xl font-bold text-white">{value}</p></Card>)}</div><Card><h2 className="mb-4 text-lg font-semibold">Quote pipeline</h2>{quotes.length ? <div className="grid gap-3">{quotes.map((quote) => <div key={quote.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-white/10 bg-slate-950/50 p-4"><div><p className="font-semibold text-white">{quote.title}</p><p className="text-sm text-slate-400">{quote.quote_number} • once-off {money(quote.once_off_total_cents)} • monthly {money(quote.monthly_total_cents)}</p></div><div className="flex items-center gap-3"><a className="rounded-lg border border-white/10 px-3 py-1 text-xs text-rapid-cyan" href={`/quotes/${quote.id}/pdf`}>PDF</a><StatusBadge value={quote.status} /><AcceptQuoteButton quote={quote} /></div></div>)}</div> : <EmptyState title="No quotes created yet" body="Create a quote from a lead or client, then accept it to automatically create a project, checklist, invoice and retainer." />}</Card></div></AppShell>;
}
