import "server-only";

import { getSupabaseAdmin, hasSupabaseConfig } from "./supabase";
import type { ActivityLog, Affiliate, Campaign, ChecklistItem, ChecklistTemplate, Client, Commission, CompanySettings, ContentItem, DocumentTemplate, FileRecord, Goal, Invoice, KnowledgeBaseItem, Lead, Message, Note, Notification, Package, Payment, Project, ProjectChecklist, Quote, QuoteItem, Referral, Retainer, Role, Service, SupportTicket, Task, User } from "./types";

export async function tableCount(table: string, filters?: Record<string, string | number | boolean | null>) {
  if (!hasSupabaseConfig()) return 0;
  const supabase = getSupabaseAdmin();
  let query = supabase.from(table).select("id", { count: "exact", head: true });
  for (const [key, value] of Object.entries(filters ?? {})) query = query.eq(key, value);
  const { count, error } = await query;
  if (error) return 0;
  return count ?? 0;
}

export async function listUsers() { if (!hasSupabaseConfig()) return [] as User[]; const { data } = await getSupabaseAdmin().from("users").select("*, role:roles(*)").order("created_at", { ascending: false }); return (data ?? []) as User[]; }
export async function listRoles() { if (!hasSupabaseConfig()) return [] as Role[]; const { data } = await getSupabaseAdmin().from("roles").select("*").order("name"); return (data ?? []) as Role[]; }
export async function listLeads() { if (!hasSupabaseConfig()) return [] as Lead[]; const { data } = await getSupabaseAdmin().from("leads").select("*, assignee:users!leads_assigned_to_fkey(id,name)").is("archived_at", null).is("converted_client_id", null).order("updated_at", { ascending: false }); return (data ?? []) as Lead[]; }
export async function listAllLeadsForReporting() { if (!hasSupabaseConfig()) return [] as Lead[]; const { data } = await getSupabaseAdmin().from("leads").select("*, assignee:users!leads_assigned_to_fkey(id,name)").order("updated_at", { ascending: false }); return (data ?? []) as Lead[]; }
export async function getLead(id: string) { if (!hasSupabaseConfig()) return null; const { data } = await getSupabaseAdmin().from("leads").select("*, assignee:users!leads_assigned_to_fkey(id,name)").eq("id", id).maybeSingle(); return data as Lead | null; }
export async function listClients() { if (!hasSupabaseConfig()) return [] as Client[]; const { data } = await getSupabaseAdmin().from("clients").select("*").is("archived_at", null).order("updated_at", { ascending: false }); return (data ?? []) as Client[]; }
export async function getClient(id: string) { if (!hasSupabaseConfig()) return null; const { data } = await getSupabaseAdmin().from("clients").select("*").eq("id", id).maybeSingle(); return data as Client | null; }
export async function listTasks() { if (!hasSupabaseConfig()) return [] as Task[]; const { data } = await getSupabaseAdmin().from("tasks").select("*, assignee:users!tasks_assigned_to_fkey(id,name)").order("updated_at", { ascending: false }); return (data ?? []) as Task[]; }
export async function getTask(id: string) { if (!hasSupabaseConfig()) return null; const { data } = await getSupabaseAdmin().from("tasks").select("*, assignee:users!tasks_assigned_to_fkey(id,name)").eq("id", id).maybeSingle(); return data as Task | null; }
export async function listServices() { if (!hasSupabaseConfig()) return [] as Service[]; const { data } = await getSupabaseAdmin().from("services").select("*").order("name"); return (data ?? []) as Service[]; }
export async function listPackages() { if (!hasSupabaseConfig()) return [] as Package[]; const { data } = await getSupabaseAdmin().from("packages").select("*").order("name"); return (data ?? []) as Package[]; }
export async function recentActivity(limit = 8) { if (!hasSupabaseConfig()) return [] as ActivityLog[]; const { data } = await getSupabaseAdmin().from("activity_logs").select("*").order("created_at", { ascending: false }).limit(limit); return (data ?? []) as ActivityLog[]; }
export async function activityByActor(actorId: string, limit = 8) { if (!hasSupabaseConfig()) return [] as ActivityLog[]; const { data } = await getSupabaseAdmin().from("activity_logs").select("*").eq("actor_id", actorId).order("created_at", { ascending: false }).limit(limit); return (data ?? []) as ActivityLog[]; }
export async function notificationsForUser(userId: string, limit = 10) { if (!hasSupabaseConfig()) return [] as Notification[]; const { data } = await getSupabaseAdmin().from("notifications").select("*").or(`user_id.eq.${userId},user_id.is.null`).order("created_at", { ascending: false }).limit(limit); return (data ?? []) as Notification[]; }
export async function listDirectMessages(userId: string) { if (!hasSupabaseConfig()) return [] as Message[]; const { data } = await getSupabaseAdmin().from("messages").select("*, sender:users!messages_sender_id_fkey(id,name)").eq("audience", "DIRECT").or(`sender_id.eq.${userId},recipient_id.eq.${userId}`).order("created_at", { ascending: true }); return (data ?? []) as Message[]; }
export async function listBroadcastMessages(limit = 50) { if (!hasSupabaseConfig()) return [] as Message[]; const { data } = await getSupabaseAdmin().from("messages").select("*, sender:users!messages_sender_id_fkey(id,name)").eq("audience", "BROADCAST").order("created_at", { ascending: true }).limit(limit); return (data ?? []) as Message[]; }
export async function unreadMessageCount(userId: string) { if (!hasSupabaseConfig()) return 0; const { count } = await getSupabaseAdmin().from("messages").select("id", { count: "exact", head: true }).eq("audience", "DIRECT").eq("recipient_id", userId).is("read_at", null); return count ?? 0; }
export async function listGoals() { if (!hasSupabaseConfig()) return [] as Goal[]; const { data } = await getSupabaseAdmin().from("goals").select("*").order("created_at", { ascending: false }); return (data ?? []) as Goal[]; }
export async function listSelfNotes(userId: string) { if (!hasSupabaseConfig()) return [] as Note[]; const { data } = await getSupabaseAdmin().from("notes").select("*").eq("entity_type", "USER").eq("entity_id", userId).order("created_at", { ascending: false }); return (data ?? []) as Note[]; }
export async function genericList<T>(table: string, order = "updated_at") { if (!hasSupabaseConfig()) return [] as T[]; const { data } = await getSupabaseAdmin().from(table).select("*").order(order, { ascending: false }); return (data ?? []) as T[]; }
export async function getProject(id: string) { if (!hasSupabaseConfig()) return null; const { data } = await getSupabaseAdmin().from("projects").select("*").eq("id", id).maybeSingle(); return data as Project | null; }
export async function getProjectChecklist(projectId: string) { if (!hasSupabaseConfig()) return [] as ProjectChecklist[]; const { data } = await getSupabaseAdmin().from("project_checklists").select("*").eq("project_id", projectId).order("created_at"); return (data ?? []) as ProjectChecklist[]; }
export async function listNotes(filters: { leadId?: string; clientId?: string; projectId?: string; entityId?: string }) { if (!hasSupabaseConfig()) return [] as Note[]; let query = getSupabaseAdmin().from("notes").select("*").order("created_at", { ascending: false }); if (filters.leadId) query = query.eq("lead_id", filters.leadId); if (filters.clientId) query = query.eq("client_id", filters.clientId); if (filters.projectId) query = query.eq("project_id", filters.projectId); if (filters.entityId) query = query.eq("entity_id", filters.entityId); const { data } = await query; return (data ?? []) as Note[]; }
export async function listFiles(filters: { leadId?: string; clientId?: string; projectId?: string; knowledgeBaseItemId?: string; knowledgeBaseItemIds?: string[]; entityId?: string }) { if (!hasSupabaseConfig()) return [] as FileRecord[]; if (filters.knowledgeBaseItemIds && !filters.knowledgeBaseItemIds.length) return [] as FileRecord[]; let query = getSupabaseAdmin().from("files").select("*").order("created_at", { ascending: false }); if (filters.leadId) query = query.eq("lead_id", filters.leadId); if (filters.clientId) query = query.eq("client_id", filters.clientId); if (filters.projectId) query = query.eq("project_id", filters.projectId); if (filters.knowledgeBaseItemId) query = query.eq("knowledge_base_item_id", filters.knowledgeBaseItemId); if (filters.knowledgeBaseItemIds?.length) query = query.in("knowledge_base_item_id", filters.knowledgeBaseItemIds); if (filters.entityId) query = query.eq("entity_id", filters.entityId); const { data } = await query; return (data ?? []) as FileRecord[]; }
export async function listQuoteItems(quoteId: string) { if (!hasSupabaseConfig()) return [] as QuoteItem[]; const { data } = await getSupabaseAdmin().from("quote_items").select("*").eq("quote_id", quoteId).order("sort_order"); return (data ?? []) as QuoteItem[]; }
export async function listInvoiceItems(invoiceId: string) { if (!hasSupabaseConfig()) return [] as import("./types").InvoiceItem[]; const { data } = await getSupabaseAdmin().from("invoice_items").select("*").eq("invoice_id", invoiceId).order("sort_order"); return (data ?? []) as import("./types").InvoiceItem[]; }
export async function listChecklistTemplates() { if (!hasSupabaseConfig()) return [] as ChecklistTemplate[]; const { data } = await getSupabaseAdmin().from("checklist_templates").select("*").order("name"); return (data ?? []) as ChecklistTemplate[]; }
export async function listChecklistItems() { if (!hasSupabaseConfig()) return [] as ChecklistItem[]; const { data } = await getSupabaseAdmin().from("checklist_items").select("*").order("sort_order"); return (data ?? []) as ChecklistItem[]; }
export async function listPayments() { return genericList<Payment>("payments"); }
export async function listReferrals() { return genericList<Referral>("referrals"); }
export async function listCommissions() { return genericList<Commission>("commissions"); }
export async function listCompanySettings() { if (!hasSupabaseConfig()) return null; const { data } = await getSupabaseAdmin().from("company_settings").select("*").eq("id", true).maybeSingle(); return data as CompanySettings | null; }
export async function listDocumentTemplates() { return genericList<DocumentTemplate>("document_templates"); }
export async function listPayrollItems() { if (!hasSupabaseConfig()) return [] as import("./types").PayrollItem[]; const { data } = await getSupabaseAdmin().from("payroll_items").select("*, user:users(id,name,title)").order("created_at", { ascending: false }); return (data ?? []) as import("./types").PayrollItem[]; }

export type ModuleData = { quotes: Quote[]; projects: Project[]; invoices: Invoice[]; retainers: Retainer[]; tickets: SupportTicket[]; affiliates: Affiliate[]; campaigns: Campaign[]; content: ContentItem[]; kb: KnowledgeBaseItem[]; };
