function clean(value: string) {
  return value.replace(/[()\\]/g, "").replace(/\r?\n/g, " ").slice(0, 130);
}

function pdfText(value: string) {
  return clean(value).replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}

function text(x: number, y: number, size: number, value: string, color = "1 1 1") {
  return `BT ${color} rg /F1 ${size} Tf ${x} ${y} Td (${pdfText(value)}) Tj ET`;
}

function rect(x: number, y: number, width: number, height: number, color: string) {
  return `${color} rg ${x} ${y} ${width} ${height} re f`;
}

export type PdfLineItem = {
  description: string;
  quantity?: number;
  onceOff?: string;
  monthly?: string;
  amount?: string;
  status?: string;
};

export type BrandedPdfInput = {
  kind: "Quote" | "Invoice";
  number: string;
  title: string;
  status: string;
  companyName?: string | null;
  billingEmail?: string | null;
  clientName?: string | null;
  clientEmail?: string | null;
  meta: string[];
  items: PdfLineItem[];
  totals: string[];
  footer?: string | null;
  paymentDetails?: string[];
};

export function brandedPdf(input: BrandedPdfInput) {
  const commands: string[] = [
    rect(0, 0, 595, 842, "0.02 0.04 0.09"),
    rect(0, 705, 595, 137, "0.05 0.13 0.28"),
    rect(385, 705, 210, 137, "0.03 0.68 0.86"),
    rect(38, 666, 519, 1.2, "0.15 0.49 1"),
    text(46, 786, 28, "Appellize AI", "1 1 1"),
    text(48, 765, 10, input.companyName ?? "Rapid Rise AI", "0.78 0.88 1"),
    text(430, 785, 26, input.kind.toUpperCase(), "0.02 0.04 0.09"),
    text(430, 763, 12, input.number, "0.02 0.04 0.09"),
    text(46, 704, 18, input.title, "1 1 1"),
    text(46, 682, 10, `Status: ${input.status}`, "0.56 0.8 1"),
    text(360, 682, 10, input.billingEmail ? `Billing: ${input.billingEmail}` : "Billing details in Rapid Rise OS", "0.78 0.88 1"),
    rect(38, 548, 247, 92, "0.07 0.1 0.18"),
    rect(310, 548, 247, 92, "0.07 0.1 0.18"),
    text(54, 616, 10, "Prepared for", "0.56 0.8 1"),
    text(54, 594, 16, input.clientName ?? "Client", "1 1 1"),
    text(54, 574, 10, input.clientEmail ?? "", "0.72 0.78 0.88"),
    text(326, 616, 10, "Document details", "0.56 0.8 1"),
  ];

  input.meta.slice(0, 4).forEach((line, index) => commands.push(text(326, 594 - index * 17, 10, line, "0.86 0.91 1")));

  commands.push(rect(38, 500, 519, 30, "0.08 0.2 0.39"));
  commands.push(text(54, 510, 10, "Description", "1 1 1"));
  commands.push(text(345, 510, 10, input.kind === "Quote" ? "Once-off" : "Amount", "1 1 1"));
  commands.push(text(455, 510, 10, input.kind === "Quote" ? "Monthly" : "Status", "1 1 1"));

  let y = 470;
  input.items.slice(0, 10).forEach((item, index) => {
    commands.push(rect(38, y - 9, 519, 31, index % 2 === 0 ? "0.055 0.075 0.13" : "0.07 0.095 0.16"));
    commands.push(text(54, y, 10, `${item.description}${item.quantity ? ` x${item.quantity}` : ""}`, "0.94 0.97 1"));
    commands.push(text(345, y, 10, item.onceOff ?? item.amount ?? "-", "0.94 0.97 1"));
    commands.push(text(455, y, 10, item.monthly ?? (item as { status?: string }).status ?? "-", "0.94 0.97 1"));
    y -= 34;
  });

  commands.push(rect(330, 160, 227, 78, "0.06 0.16 0.3"));
  input.totals.slice(0, 3).forEach((line, index) => commands.push(text(350, 211 - index * 22, index === 0 ? 14 : 11, line, index === 0 ? "1 1 1" : "0.78 0.88 1")));

  commands.push(rect(38, 96, 247, 112, "0.06 0.08 0.14"));
  commands.push(text(54, 184, 11, input.kind === "Invoice" ? "Payment details" : "Next steps", "0.56 0.8 1"));
  (input.paymentDetails?.length ? input.paymentDetails : ["Approve the quote to start onboarding.", "We will confirm scope, schedule and owners."]).slice(0, 5).forEach((line, index) => commands.push(text(54, 162 - index * 15, 9, line, "0.82 0.88 0.96")));

  commands.push(text(38, 55, 9, input.footer ?? "Thank you for choosing Appellize AI / Rapid Rise AI.", "0.62 0.7 0.82"));
  commands.push(text(38, 36, 8, "Generated by Rapid Rise OS", "0.34 0.44 0.6"));

  const content = commands.join("\n");
  const objects = [
    "1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj",
    "2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj",
    "3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >> endobj",
    "4 0 obj << /Type /Font /Subtype /Helvetica /BaseFont /Helvetica >> endobj",
    `5 0 obj << /Length ${content.length} >> stream\n${content}\nendstream endobj`,
  ];
  let pdf = "%PDF-1.4\n";
  const offsets = [0];
  for (const object of objects) {
    offsets.push(pdf.length);
    pdf += `${object}\n`;
  }
  const xref = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (const offset of offsets.slice(1)) pdf += `${String(offset).padStart(10, "0")} 00000 n \n`;
  pdf += `trailer << /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;
  return Buffer.from(pdf, "binary");
}

export function simplePdf(title: string, lines: string[]) {
  return brandedPdf({ kind: "Quote", number: title, title, status: "DRAFT", meta: [], items: lines.map((line) => ({ description: line })), totals: [], footer: "Generated by Rapid Rise OS" });
}
