import { AppShell } from "@/components/app-shell";
import { CampaignForm, ContentItemForm } from "@/components/forms";
import { ModalPanel } from "@/components/modal-panel";
import { Card, EmptyState, PageHeader, StatusBadge } from "@/components/ui";
import { genericList } from "@/lib/data";
import type { Campaign, ContentItem } from "@/lib/types";
export const dynamic = "force-dynamic";
export default async function Marketing() {
  const [campaigns, content] = await Promise.all([genericList<Campaign>("campaigns"), genericList<ContentItem>("content_items")]);
  return <AppShell><PageHeader eyebrow="Growth" title="Marketing & outreach" description="Track results on the main page and keep campaign/content creation in pop-ups." actions={<><ModalPanel title="Create outreach campaign" triggerLabel="Add campaign"><CampaignForm /></ModalPanel><ModalPanel title="Create content item" triggerLabel="Add content" variant="ghost"><ContentItemForm /></ModalPanel></>} /><div className="grid gap-6"><div className="grid gap-4 md:grid-cols-5">{[["Campaigns", campaigns.length], ["Contacted", campaigns.reduce((sum, campaign) => sum + campaign.number_contacted, 0)], ["Replies", campaigns.reduce((sum, campaign) => sum + campaign.replies, 0)], ["Calls booked", campaigns.reduce((sum, campaign) => sum + campaign.calls_booked, 0)], ["Content items", content.length]].map(([label, value]) => <Card key={label}><p className="text-sm text-slate-400">{label}</p><p className="mt-3 text-2xl font-bold text-white">{value}</p></Card>)}</div><Card><h2 className="mb-4 text-lg font-semibold text-white">Campaign performance</h2>{campaigns.length ? <div className="grid gap-3 md:grid-cols-2">{campaigns.map((campaign) => <div key={campaign.id} className="rounded-xl bg-white/[0.04] p-3"><p className="font-semibold text-white">{campaign.name}</p><p className="text-sm text-slate-400">{campaign.platform} • {campaign.replies} replies • {campaign.deals_closed} deals</p></div>)}</div> : <EmptyState title="No campaigns yet" body="Use Add campaign to start tracking outreach." />}</Card><Card><h2 className="mb-4 text-lg font-semibold text-white">Content performance</h2>{content.length ? <div className="grid gap-3">{content.map((item) => <div key={item.id} className="flex items-center justify-between rounded-xl bg-white/[0.04] p-3"><div><p className="font-semibold text-white">{item.title}</p><p className="text-sm text-slate-400">{item.platform ?? "Content"} • {item.leads_generated} leads</p></div><StatusBadge value={item.status} /></div>)}</div> : <EmptyState title="No content tracked" body="Use Add content to record posts, pages or assets." />}</Card></div></AppShell>;
}
