import { randomUUID } from "crypto";
import { notFound } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { FileRecordForm, NoteForm, ProjectForm, TaskForm } from "@/components/forms";
import { SubmitButton } from "@/components/submit-button";
import { Card, PageHeader, StatusBadge, inputClass } from "@/components/ui";
import { updateProjectChecklist } from "@/lib/actions";
import { genericList, getProject, getProjectChecklist, listClients, listFiles, listNotes, listUsers } from "@/lib/data";
import { dateShort } from "@/lib/format";
import type { Quote, Task } from "@/lib/types";
export const dynamic = "force-dynamic";
export default async function ProjectDetail({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const [project, clients, quotes, users, tasks, checklist, notes, files] = await Promise.all([getProject(id), listClients(), genericList<Quote>("quotes"), listUsers(), genericList<Task>("tasks"), getProjectChecklist(id), listNotes({ projectId: id }), listFiles({ projectId: id })]);
  if (!project) notFound();
  const redirectTo = `/projects/${project.id}`;
  return <AppShell><PageHeader eyebrow="Project detail" title={project.name} description="Delivery plan, checklist, tasks, notes and file links." /><div className="grid gap-6 xl:grid-cols-[1fr_0.85fr]"><div className="grid gap-6"><Card><ProjectForm project={project} clients={clients} quotes={quotes} /></Card><Card><h2 className="mb-4 text-lg font-semibold">Project checklist</h2><div className="grid gap-3">{checklist.map((item) => <form key={item.id} action={updateProjectChecklist} className="flex items-center justify-between gap-3 rounded-xl bg-white/[0.04] p-3"><input type="hidden" name="submissionKey" value={`project-checklist:${item.id}:${randomUUID()}`} /><input type="hidden" name="id" value={item.id} /><input type="hidden" name="redirectTo" value={redirectTo} /><div><p className="font-semibold text-white">{item.title}</p><p className="text-xs text-slate-500">Updated {dateShort(item.updated_at)}</p></div><select className={inputClass} name="status" defaultValue={item.status}><option value="TO_DO">To Do</option><option value="IN_PROGRESS">In Progress</option><option value="WAITING_FOR_CLIENT">Waiting for Client</option><option value="BLOCKED">Blocked</option><option value="DONE">Done</option></select><SubmitButton pendingLabel="Saving…" className="border border-white/10 bg-none bg-white/5 shadow-none">Save</SubmitButton></form>)}{!checklist.length ? <p className="text-sm text-slate-400">No checklist items yet. Create projects with starter checklists or add templates in settings.</p> : null}</div></Card><Card><h2 className="mb-4 text-lg font-semibold">Create linked task</h2><TaskForm users={users} clients={clients} projects={[{ id: project.id, name: project.name }]} redirectTo={redirectTo} /></Card></div><div className="grid gap-6"><Card><h2 className="text-lg font-semibold">Status</h2><div className="mt-4 grid gap-3 text-sm text-slate-300"><StatusBadge value={project.status} /><p>Progress: {project.progress}%</p><p>Deadline: {dateShort(project.deadline)}</p><p>Blocker: {project.blocker ?? "None"}</p><p>Open tasks: {tasks.filter((task) => task.project_id === project.id && task.status !== "DONE").length}</p></div></Card><Card><NoteForm entityType="Project" entityId={project.id} clientId={project.client_id} projectId={project.id} redirectTo={redirectTo} /><div className="mt-4 grid gap-2">{notes.map((note) => <p key={note.id} className="rounded-xl bg-white/[0.04] p-3 text-sm text-slate-300">{note.body}</p>)}</div></Card><Card><FileRecordForm entityType="Project" entityId={project.id} clientId={project.client_id} projectId={project.id} redirectTo={redirectTo} /><div className="mt-4 grid gap-2">{files.map((file) => <a key={file.id} href={file.url} className="rounded-xl bg-white/[0.04] p-3 text-sm text-rapid-cyan">{file.filename}</a>)}</div></Card></div></div></AppShell>;
}
