import Link from "next/link";
import { AppShell } from "@/components/app-shell";
import { EmptyState, LinkButton, PageHeader, StatusBadge } from "@/components/ui";
import { prisma } from "@/lib/db";
import { dateShort } from "@/lib/format";

export default async function LeadsPage({ searchParams }: { searchParams: Promise<{ q?: string; stage?: string }> }) {
  const params = await searchParams;
  const leads = await prisma.lead.findMany({ where: { archivedAt: null, ...(params.q ? { OR: [{ companyName: { contains: params.q } }, { contactName: { contains: params.q } }, { serviceInterest: { contains: params.q } }] } : {}), ...(params.stage ? { stage: params.stage } : {}) }, include: { assignedTo: true }, orderBy: { updatedAt: "desc" } });
  return <AppShell><PageHeader eyebrow="CRM" title="Leads" description="Track stages, scores, service interest, owner, next action and follow-up dates." actions={<LinkButton href="/leads/new">Create lead</LinkButton>} /><form className="mb-4 flex gap-3"><input name="q" placeholder="Search leads…" className="min-w-80 rounded-xl border border-white/10 bg-slate-950/70 px-3 py-2 text-sm" /><button className="rounded-xl border border-white/10 px-4 py-2 text-sm">Filter</button></form>{leads.length ? <div className="overflow-hidden rounded-2xl border border-white/10"><table className="w-full border-collapse bg-white/[0.035] text-sm"><thead className="bg-white/[0.06] text-left text-xs uppercase tracking-wider text-slate-400"><tr><th className="p-4">Company</th><th>Stage</th><th>Score</th><th>Service</th><th>Owner</th><th>Follow-up</th><th>Next action</th></tr></thead><tbody>{leads.map((lead) => <tr key={lead.id} className="border-t border-white/10 hover:bg-white/[0.04]"><td className="p-4"><Link className="font-semibold text-white" href={`/leads/${lead.id}`}>{lead.companyName}</Link><p className="text-xs text-slate-500">{lead.contactName}</p></td><td><StatusBadge value={lead.stage} /></td><td>{lead.score}</td><td>{lead.serviceInterest}</td><td>{lead.assignedTo?.name ?? "Unassigned"}</td><td>{dateShort(lead.followUpDate)}</td><td className="max-w-xs text-slate-400">{lead.nextAction ?? "—"}</td></tr>)}</tbody></table></div> : <EmptyState title="No leads yet" body="Create the first database-backed lead and assign an owner, stage and next action." action={<LinkButton href="/leads/new">Create lead</LinkButton>} />}</AppShell>;
}
