begin;

-- ---------------------------------------------------------------------------
-- Automatic commission reversal on refund / invoice void.
--
-- Mirror of affiliate_portal_private.create_commissions_for_paid_payment():
-- when the money that generated a commission is clawed back, the commission is
-- reversed automatically so no partner keeps a commission on revenue we did not
-- keep -- and no employee has to remember to undo it by hand (removing that
-- human-error / legal-risk surface is the whole point of the automation).
--
-- Reversal is decided at the INVOICE / revenue level, not per single payment,
-- because one invoice can have several PAID payments (a real payment plus the
-- "marked paid" safety-net auto-payment). A commission is only reversed once the
-- invoice has NO remaining PAID coverage; while any payment still stands, the
-- revenue is (at least partly) ours and a human must judge partial situations.
--
-- Reversal rules (aligned with the commission state machine in
-- lib/business-rules.ts -- terminal states are PAID / CANCELLED / DISPUTED):
--   * Commission NOT yet paid out (no payout_item, not PAID, no paid_at)
--       -> CANCELLED (clean reversal: nothing left the building). Its snapshot
--          idempotency key is freed so a genuine RE-payment re-credits it.
--   * Commission with ANY payout_item, or status PAID, or paid_at set
--       -> DISPUTED and flagged for human clawback. We NEVER silently erase
--          money that is already in flight or has been sent to a partner, and we
--          do NOT free its key (no auto re-credit until a human reconciles).
--
-- Every reversal writes an immutable audit event. Idempotent: commissions that
-- are already CANCELLED/DISPUTED are skipped, so re-firing never double-acts.
-- Single source of truth = payment status; an invoice leaving PAID propagates to
-- its PAID payments, which cascades here via the payment trigger.
-- ---------------------------------------------------------------------------

create or replace function affiliate_portal_private.reverse_commissions_for_payment(
  p_payment_id uuid,
  p_reason text
)
returns integer
language plpgsql
security definer
set search_path = ''
as $function$
declare
  inv_id uuid;
  remaining_paid_cents bigint;
  com record;
  already_paid_out boolean;
  new_status text;
  action text;
  reversed_count integer := 0;
begin
  select invoice_id into inv_id from public.payments where id = p_payment_id;
  if inv_id is null then return 0; end if;

  -- If any PAID payment still covers this invoice, the revenue has not actually
  -- been clawed back -- leave the commissions alone (partial cases are human).
  select coalesce(sum(amount_cents), 0) into remaining_paid_cents
  from public.payments where invoice_id = inv_id and status = 'PAID';
  if remaining_paid_cents > 0 then return 0; end if;

  -- Reverse every non-terminal commission generated by ANY payment on this
  -- invoice (a commission is linked to the one payment that first created it).
  for com in
    select c.id, c.affiliate_id, c.amount_cents, c.status, c.paid_at
    from public.commissions c
    join public.payments p on p.id = c.payment_id
    where p.invoice_id = inv_id
      and c.status not in ('CANCELLED', 'DISPUTED')
    for update
  loop
    already_paid_out := (com.status = 'PAID')
      or (com.paid_at is not null)
      or exists (
        select 1 from public.affiliate_portal_payout_items pit
        where pit.commission_id = com.id
      );

    if already_paid_out then
      new_status := 'DISPUTED';
      action := 'commission_clawback_required';
    else
      new_status := 'CANCELLED';
      action := 'commission_reversed_auto';
    end if;

    update public.commissions set status = new_status where id = com.id;
    reversed_count := reversed_count + 1;

    -- Clean reversal only: free the create-side idempotency marker so a genuine
    -- future payment on this invoice re-creates the commission. Rename (not
    -- delete) preserves the original snapshot for forensics. Paid-out (DISPUTED)
    -- commissions keep their key locked until a human reconciles the clawback.
    if new_status = 'CANCELLED' then
      update public.affiliate_portal_commission_snapshots
        set automation_key = 'reversed:' || com.id::text || ':' || automation_key
        where commission_id = com.id
          and automation_key is not null
          and automation_key not like 'reversed:%';
    end if;

    insert into public.affiliate_portal_audit_events
      (affiliate_id, action_type, entity_type, entity_id, previous_value, new_value)
    values (
      com.affiliate_id, action, 'commission', com.id::text,
      jsonb_build_object('status', com.status, 'amount_cents', com.amount_cents),
      jsonb_build_object(
        'payment_id', p_payment_id,
        'invoice_id', inv_id,
        'reason', p_reason,
        'previous_status', com.status,
        'new_status', new_status,
        'amount_cents', com.amount_cents,
        'already_paid_out', (new_status = 'DISPUTED')
      )
    );
  end loop;
  return reversed_count;
end
$function$;

-- Trigger on payments: PAID -> (REFUNDED / FAILED / CANCELLED) triggers a
-- reversal check for the whole invoice.
create or replace function affiliate_portal_private.reverse_commissions_on_payment_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $function$
begin
  if tg_op = 'UPDATE'
     and old.status = 'PAID'
     and new.status in ('REFUNDED', 'FAILED', 'CANCELLED') then
    perform affiliate_portal_private.reverse_commissions_for_payment(
      new.id, 'payment_' || lower(new.status));
  end if;
  return new;
end
$function$;

drop trigger if exists affiliate_portal_reverse_commissions_on_payment_change on public.payments;
create trigger affiliate_portal_reverse_commissions_on_payment_change
  after update of status on public.payments
  for each row
  execute function affiliate_portal_private.reverse_commissions_on_payment_change();

-- Trigger on invoices: a genuine claw-back (invoice -> REFUNDED / CANCELLED)
-- refunds the invoice's captured PAID payments, which cascades to commission
-- reversal via the payment trigger. Only these two states propagate: lifecycle
-- reversions (DRAFT/SENT/OVERDUE) and PART_PAID are deliberately excluded so we
-- never destructively rewrite a captured payment on a mere data correction.
create or replace function affiliate_portal_private.propagate_invoice_unpaid_to_payments()
returns trigger
language plpgsql
security definer
set search_path = ''
as $function$
begin
  -- Fire whenever an invoice ENTERS a claw-back state and still has captured
  -- (PAID) payments -- regardless of the prior status, so a void/refund is never
  -- missed just because the invoice was in an unexpected state. The status guard
  -- (REFUNDED/CANCELLED only) plus the "status='PAID'" filter keep this safe:
  -- lifecycle reversions and already-refunded payments are untouched.
  if tg_op = 'UPDATE'
     and new.status in ('REFUNDED', 'CANCELLED')
     and old.status is distinct from new.status then
    update public.payments
      set status = 'REFUNDED'
      where invoice_id = new.id and status = 'PAID';
  end if;
  return new;
end
$function$;

drop trigger if exists affiliate_portal_propagate_invoice_unpaid on public.invoices;
create trigger affiliate_portal_propagate_invoice_unpaid
  after update of status on public.invoices
  for each row
  execute function affiliate_portal_private.propagate_invoice_unpaid_to_payments();

-- ---------------------------------------------------------------------------
-- Defence in depth: pin the status vocabularies so a typo or rogue code path
-- can never write an unknown money state (must match lib/constants.ts).
-- Existing live rows already conform (verified before applying).
-- ---------------------------------------------------------------------------
alter table public.payments drop constraint if exists payments_status_allowed_check;
alter table public.payments add constraint payments_status_allowed_check
  check (status in ('PENDING', 'PAID', 'FAILED', 'REFUNDED', 'CANCELLED'));

alter table public.commissions drop constraint if exists commissions_status_allowed_check;
alter table public.commissions add constraint commissions_status_allowed_check
  check (status in ('PENDING', 'APPROVED', 'PAYABLE', 'PAID', 'CANCELLED', 'DISPUTED'));

-- Least privilege: these are trigger-only functions. They run as the table
-- owner regardless of caller, so no role needs direct EXECUTE. NOTE: the
-- protection here is the REVOKE, not the schema -- authenticated has USAGE on
-- affiliate_portal_private, so never add an EXECUTE grant to these
-- state-mutating functions.
revoke all on function affiliate_portal_private.reverse_commissions_for_payment(uuid, text) from public;
revoke all on function affiliate_portal_private.reverse_commissions_on_payment_change() from public;
revoke all on function affiliate_portal_private.propagate_invoice_unpaid_to_payments() from public;

commit;
