import { AppShell } from "@/components/app-shell";
import { FileRecordForm, KnowledgeBaseForm } from "@/components/forms";
import { ModalPanel } from "@/components/modal-panel";
import { Card, EmptyState, PageHeader, StatusBadge } from "@/components/ui";
import { genericList, listFiles } from "@/lib/data";
import type { KnowledgeBaseItem } from "@/lib/types";
export const dynamic = "force-dynamic";
export default async function Knowledge() {
  const [items, files] = await Promise.all([genericList<KnowledgeBaseItem>("knowledge_base_items"), listFiles({})]);
  const knowledgeFiles = files.filter((file) => file.entity_type === "KnowledgeBase");
  return <AppShell><PageHeader eyebrow="Procedures" title="Knowledge base" description="Browse SOPs and internal guides without page clutter. Add articles and files from action pop-ups." actions={<ModalPanel title="Add SOP / article" triggerLabel="Add article"><KnowledgeBaseForm /></ModalPanel>} /><div className="grid gap-6"><div className="grid gap-4 md:grid-cols-5">{[["Articles", items.length], ["SOPs", items.filter((item) => item.category === "SOP").length], ["Sales", items.filter((item) => item.category === "Sales").length], ["Troubleshooting", items.filter((item) => item.category === "Troubleshooting").length], ["Files", knowledgeFiles.length]].map(([label, value]) => <Card key={label}><p className="text-sm text-slate-400">{label}</p><p className="mt-3 text-2xl font-bold text-white">{value}</p></Card>)}</div><Card><h2 className="mb-4 text-lg font-semibold text-white">Articles</h2>{items.length ? <div className="grid gap-3 md:grid-cols-2">{items.map((item) => <article key={item.id} className="rounded-xl bg-white/[0.04] p-4"><div className="flex items-center justify-between"><h2 className="font-semibold text-white">{item.title}</h2><StatusBadge value={item.visibility} /></div><p className="mt-1 text-xs text-rapid-cyan">{item.category}</p><p className="mt-3 line-clamp-3 text-sm leading-6 text-slate-300">{item.body}</p><div className="mt-4 flex flex-wrap gap-2"><ModalPanel title={item.title} triggerLabel="View" variant="ghost"><article className="grid gap-4"><StatusBadge value={item.visibility} /><p className="text-xs text-rapid-cyan">{item.category}</p><p className="whitespace-pre-wrap text-sm leading-6 text-slate-300">{item.body}</p></article></ModalPanel><ModalPanel title="Upload knowledge file" triggerLabel="Upload file" variant="ghost"><FileRecordForm entityType="KnowledgeBase" entityId={item.id} redirectTo="/knowledge-base" /></ModalPanel></div></article>)}</div> : <EmptyState title="No knowledge articles" body="Use Add article to document SOPs, sales scripts and technical notes." />}</Card><Card><h2 className="mb-4 text-lg font-semibold text-white">Knowledge files</h2>{knowledgeFiles.length ? <div className="grid gap-2 md:grid-cols-2">{knowledgeFiles.map((file) => <a key={file.id} href={file.url} className="rounded-xl border border-white/10 bg-white/[0.04] p-3 text-sm text-rapid-cyan hover:border-rapid-cyan/40" target="_blank">{file.filename}</a>)}</div> : <p className="text-sm text-slate-400">No knowledge files linked yet.</p>}</Card></div></AppShell>;
}
