import { notFound } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { ActivityWorkflowForm, ClientForm, ProjectForm, QuoteForm, SupportTicketForm } from "@/components/forms";
import { ModalPanel } from "@/components/modal-panel";
import { Card, PageHeader, StatusBadge } from "@/components/ui";
import { genericList, getClient, listClients, listFiles, listLeads, listNotes, listServices, listTasks, listUsers, recentActivity } from "@/lib/data";
import { dateShort, money } from "@/lib/format";
import type { Invoice, Project, Quote, Retainer, SupportTicket } from "@/lib/types";
export const dynamic = "force-dynamic";
export default async function ClientDetail({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const [client, projects, quotes, invoices, retainers, tickets, activity, notes, files, clients, leads, services, users, tasks] = await Promise.all([getClient(id), genericList<Project>("projects"), genericList<Quote>("quotes"), genericList<Invoice>("invoices"), genericList<Retainer>("retainers"), genericList<SupportTicket>("support_tickets"), recentActivity(30), listNotes({ clientId: id }), listFiles({ clientId: id }), listClients(), listLeads(), listServices(), listUsers(), listTasks()]);
  if (!client) notFound();
  const redirectTo = `/clients/${client.id}`;
  const clientProjects = projects.filter((project) => project.client_id === client.id);
  const clientQuotes = quotes.filter((quote) => quote.client_id === client.id);
  const clientInvoices = invoices.filter((invoice) => invoice.client_id === client.id);
  const clientTickets = tickets.filter((ticket) => ticket.client_id === client.id);
  return <AppShell><PageHeader title={client.company_name} eyebrow="Client detail" description="Fast account overview with action pop-ups for edits, quotes, projects, tickets, notes and files." actions={<><ModalPanel title="Edit client" triggerLabel="Edit client" variant="ghost"><ClientForm client={client} /></ModalPanel><ModalPanel title="Activity workflow" triggerLabel="Activity" variant="ghost"><ActivityWorkflowForm entityType="Client" clientId={client.id} users={users} tasks={tasks.filter((task) => task.client_id === client.id && task.status !== "DONE")} redirectTo={redirectTo} defaultTitle={`Follow up with ${client.company_name}`} /></ModalPanel><ModalPanel title="Create quote" triggerLabel="Add quote"><QuoteForm clients={clients.filter((item) => item.id === client.id)} leads={leads} services={services} /></ModalPanel><ModalPanel title="Create project" triggerLabel="Add project" variant="ghost"><ProjectForm clients={clients.filter((item) => item.id === client.id)} quotes={clientQuotes} users={users} /></ModalPanel><ModalPanel title="Create support ticket" triggerLabel="Add ticket" variant="ghost"><SupportTicketForm clients={clients.filter((item) => item.id === client.id)} projects={clientProjects} users={users} /></ModalPanel></>} />
    <div className="grid gap-6 xl:grid-cols-[0.9fr_1.1fr]"><div className="grid gap-6 content-start"><Card><h2 className="text-lg font-semibold">Account health</h2><div className="mt-4 grid grid-cols-2 gap-3 text-sm text-slate-300"><p><StatusBadge value={client.account_status} /></p><p>MRR: {money(client.mrr_cents)}</p><p>Projects: {clientProjects.length}</p><p>Tickets: {clientTickets.length}</p><p>Retainers: {retainers.filter((retainer) => retainer.client_id === client.id).length}</p><p>Invoices: {clientInvoices.length}</p><p className="col-span-2">Next action: {client.next_action ?? "—"}</p></div></Card><Card><h2 className="mb-3 text-lg font-semibold">Quick actions</h2><ModalPanel title="Activity workflow" triggerLabel="Log note, task or file" variant="ghost"><ActivityWorkflowForm entityType="Client" clientId={client.id} users={users} tasks={tasks.filter((task) => task.client_id === client.id && task.status !== "DONE")} redirectTo={redirectTo} defaultTitle={`Follow up with ${client.company_name}`} /></ModalPanel></Card><Card><h2 className="text-lg font-semibold">Recent invoices</h2><div className="mt-4 grid gap-2">{clientInvoices.slice(0, 5).map((invoice) => <div key={invoice.id} className="flex items-center justify-between rounded-xl bg-white/[0.04] p-3 text-sm"><span>{invoice.invoice_number}</span><span>{money(invoice.amount_cents)}</span></div>)}</div></Card></div><div className="grid gap-6"><Card><h2 className="text-lg font-semibold">Projects</h2><div className="mt-4 grid gap-2">{clientProjects.slice(0, 6).map((project) => <a key={project.id} href={`/projects/${project.id}`} className="rounded-xl bg-white/[0.04] p-3 text-sm text-slate-200"><span className="font-semibold text-white">{project.name}</span><span className="ml-2 text-slate-400">{project.progress}%</span></a>)}</div></Card><Card><h2 className="text-lg font-semibold">Notes</h2><div className="mt-4 grid gap-2">{notes.slice(0, 5).map((note) => <p key={note.id} className="rounded-xl bg-white/[0.04] p-3 text-sm text-slate-300">{note.body}</p>)}</div></Card><Card><h2 className="text-lg font-semibold">Files</h2><div className="mt-4 grid gap-2">{files.map((file) => <a key={file.id} href={file.url} className="rounded-xl bg-white/[0.04] p-3 text-sm text-rapid-cyan">{file.filename}</a>)}</div></Card><Card><h2 className="text-lg font-semibold">Timeline</h2><div className="mt-4 grid gap-3">{activity.filter((item) => item.client_id === client.id).map((item) => <div key={item.id} className="rounded-xl bg-white/[0.04] p-3"><StatusBadge value={item.action} /><p className="mt-2 text-sm text-slate-300">{item.message}</p><p className="text-xs text-slate-500">{dateShort(item.created_at)}</p></div>)}</div></Card></div></div></AppShell>;
}
